FROM registry.access.redhat.com/ubi10/nginx-126:10.0

# Copy the HTML file to the directory Nginx expects in UBI
COPY index.html /opt/app-root/src/index.html

# Copy the configuration file to the standard Nginx location
USER 0
COPY nginx.conf /etc/nginx/nginx.conf
RUN chown 1001:0 /etc/nginx/nginx.conf
USER 1001

# Nginx in UBI is configured to run on port 8080
EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]

