# ---------- Builder ----------
FROM golang:1.24.11 AS builder

WORKDIR /app

# Download deps first (better caching)
COPY go.mod go.sum ./
RUN go mod download

# Copy source
COPY . .

# Build static binary (better for containers)
RUN CGO_ENABLED=0 GOOS=linux GOARCH=$TARGETARCH \
    go build \
    -ldflags="-s -w -extldflags '-static'" \
    -trimpath \
    -o guestbook-api .

# ---------- Runtime ----------
FROM registry.access.redhat.com/ubi10-minimal:10.0

WORKDIR /app

USER 1001

# Copy only compiled binary
COPY --from=builder /app/guestbook-api .

EXPOSE 8080
ENV PORT=8080

CMD ["./guestbook-api"]